//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Type
    {
        public Room_Type()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
