//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Account_Receivable = new HashSet<Account_Receivable>();
        }
    
        public int RoomId { get; set; }
        public int RoomType { get; set; }
        public int ManagerId { get; set; }
        public int MentainerId { get; set; }
        public int RoomNumber { get; set; }
        public Nullable<int> ReservationId { get; set; }
    
        public virtual ICollection<Account_Receivable> Account_Receivable { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual Room_Type Room_Type { get; set; }
    }
}
